// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1-same-level-message.proto

public final class 1SameLevelMessage {
  private 1SameLevelMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <pre>
     * small_picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    com.google.protobuf.ByteString getSmallPicture();

    /**
     * <code>bool is_profile_verified = 5;</code>
     * @return The isProfileVerified.
     */
    boolean getIsProfileVerified();

    /**
     * <pre>
     * height of person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    float getHeight();

    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    java.util.List<java.lang.String>
        getPhoneNumbersList();
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    int getPhoneNumbersCount();
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    java.lang.String getPhoneNumbers(int index);
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index);

    /**
     * <pre>
     * This is an enum, as defined above
     * </pre>
     *
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The enum numeric value on the wire for eyeColour.
     */
    int getEyeColourValue();
    /**
     * <pre>
     * This is an enum, as defined above
     * </pre>
     *
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The eyeColour.
     */
    1SameLevelMessage.Person.EyeColour getEyeColour();

    /**
     * <code>.Date birthday = 9;</code>
     * @return Whether the birthday field is set.
     */
    boolean hasBirthday();
    /**
     * <code>.Date birthday = 9;</code>
     * @return The birthday.
     */
    1SameLevelMessage.Date getBirthday();
    /**
     * <code>.Date birthday = 9;</code>
     */
    1SameLevelMessage.DateOrBuilder getBirthdayOrBuilder();
  }
  /**
   * <pre>
   * Person is used to identify users
   * across our system 
   * </pre>
   *
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      firstName_ = "";
      lastName_ = "";
      smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      eyeColour_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {

              smallPicture_ = input.readBytes();
              break;
            }
            case 40: {

              isProfileVerified_ = input.readBool();
              break;
            }
            case 53: {

              height_ = input.readFloat();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phoneNumbers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              phoneNumbers_.add(s);
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              eyeColour_ = rawValue;
              break;
            }
            case 74: {
              1SameLevelMessage.Date.Builder subBuilder = null;
              if (birthday_ != null) {
                subBuilder = birthday_.toBuilder();
              }
              birthday_ = input.readMessage(1SameLevelMessage.Date.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthday_);
                birthday_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 1SameLevelMessage.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 1SameLevelMessage.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              1SameLevelMessage.Person.class, 1SameLevelMessage.Person.Builder.class);
    }

    /**
     * <pre>
     * We currently only consider 3 eye colours
     * </pre>
     *
     * Protobuf enum {@code Person.EyeColour}
     */
    public enum EyeColour
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_EYE_COLOUR = 0;</code>
       */
      UNKNOWN_EYE_COLOUR(0),
      /**
       * <code>EYE_GREEN = 1;</code>
       */
      EYE_GREEN(1),
      /**
       * <code>EYE_BROWN = 2;</code>
       */
      EYE_BROWN(2),
      /**
       * <code>EYE_BLUE = 3;</code>
       */
      EYE_BLUE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_EYE_COLOUR = 0;</code>
       */
      public static final int UNKNOWN_EYE_COLOUR_VALUE = 0;
      /**
       * <code>EYE_GREEN = 1;</code>
       */
      public static final int EYE_GREEN_VALUE = 1;
      /**
       * <code>EYE_BROWN = 2;</code>
       */
      public static final int EYE_BROWN_VALUE = 2;
      /**
       * <code>EYE_BLUE = 3;</code>
       */
      public static final int EYE_BLUE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EyeColour valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EyeColour forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_EYE_COLOUR;
          case 1: return EYE_GREEN;
          case 2: return EYE_BROWN;
          case 3: return EYE_BLUE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EyeColour>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EyeColour> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EyeColour>() {
              public EyeColour findValueByNumber(int number) {
                return EyeColour.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return 1SameLevelMessage.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final EyeColour[] VALUES = values();

      public static EyeColour valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EyeColour(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.EyeColour)
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <pre>
     * the age as of the person's creation
     * </pre>
     *
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the first name as documented in the signup form
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SMALL_PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString smallPicture_;
    /**
     * <pre>
     * small_picture represents a small .jpg file
     * </pre>
     *
     * <code>bytes small_picture = 4;</code>
     * @return The smallPicture.
     */
    public com.google.protobuf.ByteString getSmallPicture() {
      return smallPicture_;
    }

    public static final int IS_PROFILE_VERIFIED_FIELD_NUMBER = 5;
    private boolean isProfileVerified_;
    /**
     * <code>bool is_profile_verified = 5;</code>
     * @return The isProfileVerified.
     */
    public boolean getIsProfileVerified() {
      return isProfileVerified_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private float height_;
    /**
     * <pre>
     * height of person in cms
     * </pre>
     *
     * <code>float height = 6;</code>
     * @return The height.
     */
    public float getHeight() {
      return height_;
    }

    public static final int PHONE_NUMBERS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList phoneNumbers_;
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return A list containing the phoneNumbers.
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneNumbersList() {
      return phoneNumbers_;
    }
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @return The count of phoneNumbers.
     */
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the element to return.
     * @return The phoneNumbers at the given index.
     */
    public java.lang.String getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <pre>
     * a list of phone numbers is optional to provide at signup
     * </pre>
     *
     * <code>repeated string phone_numbers = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the phoneNumbers at the given index.
     */
    public com.google.protobuf.ByteString
        getPhoneNumbersBytes(int index) {
      return phoneNumbers_.getByteString(index);
    }

    public static final int EYE_COLOUR_FIELD_NUMBER = 8;
    private int eyeColour_;
    /**
     * <pre>
     * This is an enum, as defined above
     * </pre>
     *
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The enum numeric value on the wire for eyeColour.
     */
    public int getEyeColourValue() {
      return eyeColour_;
    }
    /**
     * <pre>
     * This is an enum, as defined above
     * </pre>
     *
     * <code>.Person.EyeColour eye_colour = 8;</code>
     * @return The eyeColour.
     */
    public 1SameLevelMessage.Person.EyeColour getEyeColour() {
      @SuppressWarnings("deprecation")
      1SameLevelMessage.Person.EyeColour result = 1SameLevelMessage.Person.EyeColour.valueOf(eyeColour_);
      return result == null ? 1SameLevelMessage.Person.EyeColour.UNRECOGNIZED : result;
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 9;
    private 1SameLevelMessage.Date birthday_;
    /**
     * <code>.Date birthday = 9;</code>
     * @return Whether the birthday field is set.
     */
    public boolean hasBirthday() {
      return birthday_ != null;
    }
    /**
     * <code>.Date birthday = 9;</code>
     * @return The birthday.
     */
    public 1SameLevelMessage.Date getBirthday() {
      return birthday_ == null ? 1SameLevelMessage.Date.getDefaultInstance() : birthday_;
    }
    /**
     * <code>.Date birthday = 9;</code>
     */
    public 1SameLevelMessage.DateOrBuilder getBirthdayOrBuilder() {
      return getBirthday();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        output.writeBytes(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        output.writeBool(5, isProfileVerified_);
      }
      if (height_ != 0F) {
        output.writeFloat(6, height_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phoneNumbers_.getRaw(i));
      }
      if (eyeColour_ != 1SameLevelMessage.Person.EyeColour.UNKNOWN_EYE_COLOUR.getNumber()) {
        output.writeEnum(8, eyeColour_);
      }
      if (birthday_ != null) {
        output.writeMessage(9, getBirthday());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!smallPicture_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, smallPicture_);
      }
      if (isProfileVerified_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isProfileVerified_);
      }
      if (height_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, height_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phoneNumbers_.size(); i++) {
          dataSize += computeStringSizeNoTag(phoneNumbers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhoneNumbersList().size();
      }
      if (eyeColour_ != 1SameLevelMessage.Person.EyeColour.UNKNOWN_EYE_COLOUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, eyeColour_);
      }
      if (birthday_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getBirthday());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 1SameLevelMessage.Person)) {
        return super.equals(obj);
      }
      1SameLevelMessage.Person other = (1SameLevelMessage.Person) obj;

      if (getAge()
          != other.getAge()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getSmallPicture()
          .equals(other.getSmallPicture())) return false;
      if (getIsProfileVerified()
          != other.getIsProfileVerified()) return false;
      if (java.lang.Float.floatToIntBits(getHeight())
          != java.lang.Float.floatToIntBits(
              other.getHeight())) return false;
      if (!getPhoneNumbersList()
          .equals(other.getPhoneNumbersList())) return false;
      if (eyeColour_ != other.eyeColour_) return false;
      if (hasBirthday() != other.hasBirthday()) return false;
      if (hasBirthday()) {
        if (!getBirthday()
            .equals(other.getBirthday())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + SMALL_PICTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSmallPicture().hashCode();
      hash = (37 * hash) + IS_PROFILE_VERIFIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsProfileVerified());
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeight());
      if (getPhoneNumbersCount() > 0) {
        hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumbersList().hashCode();
      }
      hash = (37 * hash) + EYE_COLOUR_FIELD_NUMBER;
      hash = (53 * hash) + eyeColour_;
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 1SameLevelMessage.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1SameLevelMessage.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1SameLevelMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(1SameLevelMessage.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Person is used to identify users
     * across our system 
     * </pre>
     *
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        1SameLevelMessage.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 1SameLevelMessage.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 1SameLevelMessage.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                1SameLevelMessage.Person.class, 1SameLevelMessage.Person.Builder.class);
      }

      // Construct using 1SameLevelMessage.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        age_ = 0;

        firstName_ = "";

        lastName_ = "";

        smallPicture_ = com.google.protobuf.ByteString.EMPTY;

        isProfileVerified_ = false;

        height_ = 0F;

        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        eyeColour_ = 0;

        if (birthdayBuilder_ == null) {
          birthday_ = null;
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 1SameLevelMessage.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public 1SameLevelMessage.Person getDefaultInstanceForType() {
        return 1SameLevelMessage.Person.getDefaultInstance();
      }

      @java.lang.Override
      public 1SameLevelMessage.Person build() {
        1SameLevelMessage.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 1SameLevelMessage.Person buildPartial() {
        1SameLevelMessage.Person result = new 1SameLevelMessage.Person(this);
        int from_bitField0_ = bitField0_;
        result.age_ = age_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.smallPicture_ = smallPicture_;
        result.isProfileVerified_ = isProfileVerified_;
        result.height_ = height_;
        if (((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = phoneNumbers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.phoneNumbers_ = phoneNumbers_;
        result.eyeColour_ = eyeColour_;
        if (birthdayBuilder_ == null) {
          result.birthday_ = birthday_;
        } else {
          result.birthday_ = birthdayBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 1SameLevelMessage.Person) {
          return mergeFrom((1SameLevelMessage.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(1SameLevelMessage.Person other) {
        if (other == 1SameLevelMessage.Person.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getSmallPicture() != com.google.protobuf.ByteString.EMPTY) {
          setSmallPicture(other.getSmallPicture());
        }
        if (other.getIsProfileVerified() != false) {
          setIsProfileVerified(other.getIsProfileVerified());
        }
        if (other.getHeight() != 0F) {
          setHeight(other.getHeight());
        }
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
        if (other.eyeColour_ != 0) {
          setEyeColourValue(other.getEyeColourValue());
        }
        if (other.hasBirthday()) {
          mergeBirthday(other.getBirthday());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        1SameLevelMessage.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (1SameLevelMessage.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the age as of the person's creation
       * </pre>
       *
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the first name as documented in the signup form
       * </pre>
       *
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString smallPicture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return The smallPicture.
       */
      public com.google.protobuf.ByteString getSmallPicture() {
        return smallPicture_;
      }
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @param value The smallPicture to set.
       * @return This builder for chaining.
       */
      public Builder setSmallPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        smallPicture_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * small_picture represents a small .jpg file
       * </pre>
       *
       * <code>bytes small_picture = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSmallPicture() {
        
        smallPicture_ = getDefaultInstance().getSmallPicture();
        onChanged();
        return this;
      }

      private boolean isProfileVerified_ ;
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @return The isProfileVerified.
       */
      public boolean getIsProfileVerified() {
        return isProfileVerified_;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @param value The isProfileVerified to set.
       * @return This builder for chaining.
       */
      public Builder setIsProfileVerified(boolean value) {
        
        isProfileVerified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_profile_verified = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsProfileVerified() {
        
        isProfileVerified_ = false;
        onChanged();
        return this;
      }

      private float height_ ;
      /**
       * <pre>
       * height of person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return The height.
       */
      public float getHeight() {
        return height_;
      }
      /**
       * <pre>
       * height of person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(float value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * height of person in cms
       * </pre>
       *
       * <code>float height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = new com.google.protobuf.LazyStringArrayList(phoneNumbers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return A list containing the phoneNumbers.
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneNumbersList() {
        return phoneNumbers_.getUnmodifiableView();
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return The count of phoneNumbers.
       */
      public int getPhoneNumbersCount() {
        return phoneNumbers_.size();
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the element to return.
       * @return The phoneNumbers at the given index.
       */
      public java.lang.String getPhoneNumbers(int index) {
        return phoneNumbers_.get(index);
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the phoneNumbers at the given index.
       */
      public com.google.protobuf.ByteString
          getPhoneNumbersBytes(int index) {
        return phoneNumbers_.getByteString(index);
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param index The index to set the value at.
       * @param value The phoneNumbers to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneNumbers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param values The phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllPhoneNumbers(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneNumbers() {
        phoneNumbers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a list of phone numbers is optional to provide at signup
       * </pre>
       *
       * <code>repeated string phone_numbers = 7;</code>
       * @param value The bytes of the phoneNumbers to add.
       * @return This builder for chaining.
       */
      public Builder addPhoneNumbersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
        return this;
      }

      private int eyeColour_ = 0;
      /**
       * <pre>
       * This is an enum, as defined above
       * </pre>
       *
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return The enum numeric value on the wire for eyeColour.
       */
      public int getEyeColourValue() {
        return eyeColour_;
      }
      /**
       * <pre>
       * This is an enum, as defined above
       * </pre>
       *
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @param value The enum numeric value on the wire for eyeColour to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColourValue(int value) {
        eyeColour_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is an enum, as defined above
       * </pre>
       *
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return The eyeColour.
       */
      public 1SameLevelMessage.Person.EyeColour getEyeColour() {
        @SuppressWarnings("deprecation")
        1SameLevelMessage.Person.EyeColour result = 1SameLevelMessage.Person.EyeColour.valueOf(eyeColour_);
        return result == null ? 1SameLevelMessage.Person.EyeColour.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * This is an enum, as defined above
       * </pre>
       *
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @param value The eyeColour to set.
       * @return This builder for chaining.
       */
      public Builder setEyeColour(1SameLevelMessage.Person.EyeColour value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eyeColour_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This is an enum, as defined above
       * </pre>
       *
       * <code>.Person.EyeColour eye_colour = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearEyeColour() {
        
        eyeColour_ = 0;
        onChanged();
        return this;
      }

      private 1SameLevelMessage.Date birthday_;
      private com.google.protobuf.SingleFieldBuilderV3<
          1SameLevelMessage.Date, 1SameLevelMessage.Date.Builder, 1SameLevelMessage.DateOrBuilder> birthdayBuilder_;
      /**
       * <code>.Date birthday = 9;</code>
       * @return Whether the birthday field is set.
       */
      public boolean hasBirthday() {
        return birthdayBuilder_ != null || birthday_ != null;
      }
      /**
       * <code>.Date birthday = 9;</code>
       * @return The birthday.
       */
      public 1SameLevelMessage.Date getBirthday() {
        if (birthdayBuilder_ == null) {
          return birthday_ == null ? 1SameLevelMessage.Date.getDefaultInstance() : birthday_;
        } else {
          return birthdayBuilder_.getMessage();
        }
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public Builder setBirthday(1SameLevelMessage.Date value) {
        if (birthdayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthday_ = value;
          onChanged();
        } else {
          birthdayBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public Builder setBirthday(
          1SameLevelMessage.Date.Builder builderForValue) {
        if (birthdayBuilder_ == null) {
          birthday_ = builderForValue.build();
          onChanged();
        } else {
          birthdayBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public Builder mergeBirthday(1SameLevelMessage.Date value) {
        if (birthdayBuilder_ == null) {
          if (birthday_ != null) {
            birthday_ =
              1SameLevelMessage.Date.newBuilder(birthday_).mergeFrom(value).buildPartial();
          } else {
            birthday_ = value;
          }
          onChanged();
        } else {
          birthdayBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public Builder clearBirthday() {
        if (birthdayBuilder_ == null) {
          birthday_ = null;
          onChanged();
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public 1SameLevelMessage.Date.Builder getBirthdayBuilder() {
        
        onChanged();
        return getBirthdayFieldBuilder().getBuilder();
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      public 1SameLevelMessage.DateOrBuilder getBirthdayOrBuilder() {
        if (birthdayBuilder_ != null) {
          return birthdayBuilder_.getMessageOrBuilder();
        } else {
          return birthday_ == null ?
              1SameLevelMessage.Date.getDefaultInstance() : birthday_;
        }
      }
      /**
       * <code>.Date birthday = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          1SameLevelMessage.Date, 1SameLevelMessage.Date.Builder, 1SameLevelMessage.DateOrBuilder> 
          getBirthdayFieldBuilder() {
        if (birthdayBuilder_ == null) {
          birthdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              1SameLevelMessage.Date, 1SameLevelMessage.Date.Builder, 1SameLevelMessage.DateOrBuilder>(
                  getBirthday(),
                  getParentForChildren(),
                  isClean());
          birthday_ = null;
        }
        return birthdayBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final 1SameLevelMessage.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 1SameLevelMessage.Person();
    }

    public static 1SameLevelMessage.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 1SameLevelMessage.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Date)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Year of date. Must be from 1 to 9999, or 0 if specifying a date without a
     * year.
     * </pre>
     *
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <pre>
     * Month of year. Must be from 1 to 12.
     * </pre>
     *
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    int getMonth();

    /**
     * <pre>
     * Day of Month. Must be from 1 to 31.
     * </pre>
     *
     * <code>int32 day = 3;</code>
     * @return The day.
     */
    int getDay();
  }
  /**
   * Protobuf type {@code Date}
   */
  public  static final class Date extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Date)
      DateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Date.newBuilder() to construct.
    private Date(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Date() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Date();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Date(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              year_ = input.readInt32();
              break;
            }
            case 16: {

              month_ = input.readInt32();
              break;
            }
            case 24: {

              day_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 1SameLevelMessage.internal_static_Date_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 1SameLevelMessage.internal_static_Date_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              1SameLevelMessage.Date.class, 1SameLevelMessage.Date.Builder.class);
    }

    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    /**
     * <pre>
     * Year of date. Must be from 1 to 9999, or 0 if specifying a date without a
     * year.
     * </pre>
     *
     * <code>int32 year = 1;</code>
     * @return The year.
     */
    public int getYear() {
      return year_;
    }

    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    /**
     * <pre>
     * Month of year. Must be from 1 to 12.
     * </pre>
     *
     * <code>int32 month = 2;</code>
     * @return The month.
     */
    public int getMonth() {
      return month_;
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private int day_;
    /**
     * <pre>
     * Day of Month. Must be from 1 to 31.
     * </pre>
     *
     * <code>int32 day = 3;</code>
     * @return The day.
     */
    public int getDay() {
      return day_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (year_ != 0) {
        output.writeInt32(1, year_);
      }
      if (month_ != 0) {
        output.writeInt32(2, month_);
      }
      if (day_ != 0) {
        output.writeInt32(3, day_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, year_);
      }
      if (month_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, month_);
      }
      if (day_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, day_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 1SameLevelMessage.Date)) {
        return super.equals(obj);
      }
      1SameLevelMessage.Date other = (1SameLevelMessage.Date) obj;

      if (getYear()
          != other.getYear()) return false;
      if (getMonth()
          != other.getMonth()) return false;
      if (getDay()
          != other.getDay()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 1SameLevelMessage.Date parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Date parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Date parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Date parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Date parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1SameLevelMessage.Date parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1SameLevelMessage.Date parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Date parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1SameLevelMessage.Date parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Date parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1SameLevelMessage.Date parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1SameLevelMessage.Date parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(1SameLevelMessage.Date prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Date}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Date)
        1SameLevelMessage.DateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 1SameLevelMessage.internal_static_Date_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 1SameLevelMessage.internal_static_Date_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                1SameLevelMessage.Date.class, 1SameLevelMessage.Date.Builder.class);
      }

      // Construct using 1SameLevelMessage.Date.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        year_ = 0;

        month_ = 0;

        day_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 1SameLevelMessage.internal_static_Date_descriptor;
      }

      @java.lang.Override
      public 1SameLevelMessage.Date getDefaultInstanceForType() {
        return 1SameLevelMessage.Date.getDefaultInstance();
      }

      @java.lang.Override
      public 1SameLevelMessage.Date build() {
        1SameLevelMessage.Date result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 1SameLevelMessage.Date buildPartial() {
        1SameLevelMessage.Date result = new 1SameLevelMessage.Date(this);
        result.year_ = year_;
        result.month_ = month_;
        result.day_ = day_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 1SameLevelMessage.Date) {
          return mergeFrom((1SameLevelMessage.Date)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(1SameLevelMessage.Date other) {
        if (other == 1SameLevelMessage.Date.getDefaultInstance()) return this;
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (other.getMonth() != 0) {
          setMonth(other.getMonth());
        }
        if (other.getDay() != 0) {
          setDay(other.getDay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        1SameLevelMessage.Date parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (1SameLevelMessage.Date) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int year_ ;
      /**
       * <pre>
       * Year of date. Must be from 1 to 9999, or 0 if specifying a date without a
       * year.
       * </pre>
       *
       * <code>int32 year = 1;</code>
       * @return The year.
       */
      public int getYear() {
        return year_;
      }
      /**
       * <pre>
       * Year of date. Must be from 1 to 9999, or 0 if specifying a date without a
       * year.
       * </pre>
       *
       * <code>int32 year = 1;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Year of date. Must be from 1 to 9999, or 0 if specifying a date without a
       * year.
       * </pre>
       *
       * <code>int32 year = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <pre>
       * Month of year. Must be from 1 to 12.
       * </pre>
       *
       * <code>int32 month = 2;</code>
       * @return The month.
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <pre>
       * Month of year. Must be from 1 to 12.
       * </pre>
       *
       * <code>int32 month = 2;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(int value) {
        
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Month of year. Must be from 1 to 12.
       * </pre>
       *
       * <code>int32 month = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <pre>
       * Day of Month. Must be from 1 to 31.
       * </pre>
       *
       * <code>int32 day = 3;</code>
       * @return The day.
       */
      public int getDay() {
        return day_;
      }
      /**
       * <pre>
       * Day of Month. Must be from 1 to 31.
       * </pre>
       *
       * <code>int32 day = 3;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(int value) {
        
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Day of Month. Must be from 1 to 31.
       * </pre>
       *
       * <code>int32 day = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Date)
    }

    // @@protoc_insertion_point(class_scope:Date)
    private static final 1SameLevelMessage.Date DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 1SameLevelMessage.Date();
    }

    public static 1SameLevelMessage.Date getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Date>
        PARSER = new com.google.protobuf.AbstractParser<Date>() {
      @java.lang.Override
      public Date parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Date(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Date> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Date> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 1SameLevelMessage.Date getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Date_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Date_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0321-same-level-message.proto\"\250\002\n\006Person\022" +
      "\013\n\003age\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast" +
      "_name\030\003 \001(\t\022\025\n\rsmall_picture\030\004 \001(\014\022\033\n\023is" +
      "_profile_verified\030\005 \001(\010\022\016\n\006height\030\006 \001(\002\022" +
      "\025\n\rphone_numbers\030\007 \003(\t\022%\n\neye_colour\030\010 \001" +
      "(\0162\021.Person.EyeColour\022\027\n\010birthday\030\t \001(\0132" +
      "\005.Date\"O\n\tEyeColour\022\026\n\022UNKNOWN_EYE_COLOU" +
      "R\020\000\022\r\n\tEYE_GREEN\020\001\022\r\n\tEYE_BROWN\020\002\022\014\n\010EYE" +
      "_BLUE\020\003\"0\n\004Date\022\014\n\004year\030\001 \001(\005\022\r\n\005month\030\002" +
      " \001(\005\022\013\n\003day\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Age", "FirstName", "LastName", "SmallPicture", "IsProfileVerified", "Height", "PhoneNumbers", "EyeColour", "Birthday", });
    internal_static_Date_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Date_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Date_descriptor,
        new java.lang.String[] { "Year", "Month", "Day", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
